### DISCUSSION TITLE
"CatalogSourceBundle" API for Wrapping "Bundle of Bundles"

### DISCUSSION THREAD

**Discussion by tylerslaton** [operator-framework/rukpak#257] [Ideas]
In a recent working group meeting, we began discussing a Deppy-like component (outlined [here](https://hackmd.io/hppR60SiRGKPcqKQuByvVg?view#Deppy)) which would be responsible for handling resolving catalogs for Rukpak. During the discussion it was mentioned that we may start to look at `Rukpak` catalogs to be a `Bundle` of `Bundle`s that would then get resolved like normal by a provisioner. However, the point was brought up that this may be confusing for a user as they are sourcing a catalog using the `Bundle` API. I was thinking on this issue and wanted to see what we thought about this idea. 

What if we added two new core Rukpak `CRD`s, `CatalogSourceBundle` and `CatalogSourceBundleInstance` (name subject to change), to the core `Rukpak` `CRD`s?

Essentially this would be an implementation of a `Bundle` interface where they share similar properties but are named differently (and could include other catalog specific metadata)?. The `CatalogSourceBundleInstance` could act as a `Subscription` does today and allow for things like constraints, metadata, etc. As a result, users can now use two separate API's but under-the-hood the resources operate extremely similarly and share the same provisioner-style of resolution.

I envision this looking something along these lines:

```yaml
apiVersion: core.rukpak.io/v1alpha1
kind: CatalogSourceBundle
metadata:
  name: my-catalog
spec:
  source:
    type: image # Could add a new source of file to read FBC's directly
    image:
      ref: my-bundle@sha256:xyz123
  provisionerClassName: core.rukpak.io/plain-catalog
```

With a `CatalogSourceBundleInstance` looking like:

```yaml
apiVersion: core.rukpak.io/v1alpha1
kind: CatalogSourceBundleInstance
metadata:
  name: my-catalog-source
spec:
  bundleName: my-bundle
  version: v0.0.1 # Example of metadata we could add
  provisionerClassName: core.rukpak.io/plain-catalog
```

This would result in a `BundleInstance` (potentially with an embedded `Bundle` for the resolved catalog item) being unpacked/instantiated on the cluster.
