### ISSUE TITLE
Add support for sourcing a git repository for Bundle content

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#117]
The Bundle API right now only supports unpacking a single source type right now: a remote container image, which is configured using the spec.Image field in the Bundle CRD. We'll need to onboard new source types, which can be enabled on a per-provisioner-basis, in the Bundle's spec. The e2e strawman outlined the potential for a series of source references that can be configured using a prefix-based approach:

```yaml
kind: Bundle
metadata: 
  name: plumbus-operator.v0.9.3
spec:
  class: deppy.resolveset
  refs:
  - file://content
  volumeMounts:
  - mountPath: /content
    configMap:
      name: local 
      namespace: plumbus
```

The goal here would be able to expose and implement the ability to point to a git repository as a valid Bundle source. In the context of the plain+v0 provisioner, users could source Bundle contents that live in a repositories root manifests/ directory, and that directory contains a series of static YAML manifests, and the provisioner is responsible for sourcing and unpacking those contents on-cluster.
