### ISSUE TITLE
Improve the UX around a BI that reference a Bundle that have been removed

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#129]
Right now when a user creates a set of Bundle/BI resources, the spec.BundleName Bundle resource has been deleted and the BI controller has already stamped out those resources, then the BI controller will report a failed Bundle lookup in it's status:

```bash
$ k apply -f samples/olm-crds.yaml
$ # wait until the BI is reporting a successful installation
$ k get bundleinstances
NAME       DESIRED BUNDLE     INSTALLED BUNDLE   INSTALL STATE      AGE
olm-crds   olm-v0.20.0-crds   olm-v0.20.0-crds   InstallSucceeded   22s
$ k delete bundle olm-v0.20.0-crds
$ k get bundleinstances -o yaml
status:
  conditions:
  - lastTransitionTime: "2022-03-08T16:12:53Z"
    message: Bundle.core.rukpak.io "olm-v0.20.0-crds" not found
    reason: BundleLookupFailed
    status: "False"
    type: Installed
```

The problem with this status condition is that the BI controller places the BI owner references on the underlying Bundle resources, so the result is these resources still existing on cluster:

```bash
$ k get crds -l core.rukpak.io/owner-kind=BundleInstance,core.rukpak.io/owner-name=olm-crds
NAME                                          CREATED AT
catalogsources.operators.coreos.com           2022-03-08T16:12:31Z
clusterserviceversions.operators.coreos.com   2022-03-08T16:12:31Z
installplans.operators.coreos.com             2022-03-08T16:12:31Z
olmconfigs.operators.coreos.com               2022-03-08T16:12:31Z
operatorconditions.operators.coreos.com       2022-03-08T16:12:31Z
operatorgroups.operators.coreos.com           2022-03-08T16:12:31Z
operators.operators.coreos.com                2022-03-08T16:12:31Z
subscriptions.operators.coreos.com            2022-03-08T16:12:31Z
```

**Comment by exdx** [comment]
If we flipped the status.Condition.status to "True" would it be more clear what the issue is? That the bundle is not found, but the install was successful. I'm wondering if we need a new status.Condition.reason, or something else to convey this edge-case scenario to the user.

**Comment by timflannagan** [comment]
Note: this is a potential 0.3 candidate when grooming this 0.2 milestone backlog further.

**Comment by exdx** [comment]
> I think that would make this clearer from a UX perspective. Did we want to just do that and not update the core logic of what happens when a BI's Bundle is deleted? 

To me, flipping the bundle.condition.status in this case seems to make the error more clear. Maybe that's all we need for now. But curious to hear other's thoughts. 

> Should deleting a Bundle also delete all BI's?

No, removing the Bundle should not remove the BI as the two resources are conceptually separate (the sourcing of content and the application of content). However the concept of cascade deletion is intuitive and potentially useful. I'm wondering if in the case of the embedded bundle spec in the BI, the bundle would get ownerref'd by the BI in that case, so removing one would remove the other (see #73). Removing a BI causes removal of a bundle there is some argument for -- but in the other case where removing a bundle removes a BI I don't think we will support, since the BI logically comes after.

**Comment by tylerslaton** [comment]
Okay, I see where you're getting at now. Would it make sense for us, in the status, to also include a "InstallationSucceeded" status? Right now if you delete the Bundle for a BundleInstance, it just has this status section:

```yaml
status:
  conditions:
  - lastTransitionTime: "2022-03-14T19:19:16Z"
    message: Bundle.core.rukpak.io "combo-v0.0.1" not found
    reason: BundleLookupFailed
    status: "False"
    type: Installed
```

**Comment by exdx** [comment]
Yes, I think adding InstallationSucceeded/InstallationFailed status conditions would be great 👍

**Comment by joelanford** [comment]
You should never have two conditions with the same `type`. Type is effectively the key in the listMap.

BUT -- this is definitely a case where two different types make sense. E.g.
```yaml
status:
  conditions:
  - lastTransitionTime: "2022-03-14T19:19:16Z"
    message: Bundle.core.rukpak.io "combo-v0.0.1" not found
    reason: BundleLookupFailed
    status: "False"
    type: HasValidBundle
  - lastTransitionTime: "2022-03-14T19:10:49Z"
    message: ""
    reason: InstallationSucceeded
    status: "True"
    type: Installed
  installedBundleName: combo-v0.0.1
```
