### ISSUE TITLE
The plain-v0 provisioner cannot rollout Bundles containing CRDs and instances of those CRDs

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#131]
When deploying the plain-v0 provisioner using `make run KIND_CLUSTER_NAME=kind` and creating the following Bundle/BundleInstance resources:

```yaml
apiVersion: core.rukpak.io/v1alpha1
kind: Bundle
metadata:
  name: olm-v0.20.0
spec:
  image: quay.io/tflannag/olm-plain-bundle:olm-v0.20.0-combined
  provisionerClassName: core.rukpak.io/plain-v0

---

apiVersion: core.rukpak.io/v1alpha1
kind: BundleInstance
metadata:
  name: olm-v0.20.0
spec:
  bundleName: olm-v0.20.0
  provisionerClassName: core.rukpak.io/plain-v0
```

The provisioner fails to rollout that Bundle, with the BundleInstance reporting a failed state:

```bash
$ k get bundleinstances olm-v0.20.0 -o yaml
apiVersion: core.rukpak.io/v1alpha1
kind: BundleInstance
metadata:
  ...
spec:
  bundleName: olm-v0.20.0
  provisionerClassName: core.rukpak.io/plain-v0
status:
  conditions:
  - lastTransitionTime: "2022-03-08T17:42:25Z"
    message: 'error while running post render on files: [unable to recognize "": no
      matches for kind "CatalogSource" in version "operators.coreos.com/v1alpha1",
      unable to recognize "": no matches for kind "ClusterServiceVersion" in version
      "operators.coreos.com/v1alpha1", unable to recognize "": no matches for kind
      "OLMConfig" in version "operators.coreos.com/v1", unable to recognize "": no
      matches for kind "OperatorGroup" in version "operators.coreos.com/v1"]'
    reason: InstallFailed
    status: "False"
    type: Installed
```
