### ISSUE TITLE
Introduce CRD schema validation for the union-based Bundle API

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#216]
Examine how to possibly incorporate CRD-schema level validation for the union type semantics exposed through the new source field. If not possible, move git-based bundle level validation into the bundle webhook.

**Comment by akihikokuroda** [comment]
https://github.com/operator-framework/rukpak/pull/217#issuecomment-1089096105

**Comment by akihikokuroda** [comment]
I tried the `oneOf` but I couldn't make it work.

**Comment by akihikokuroda** [comment]
I could make the validation works for `ref`.  The source still needs the webhook.  I could also make the bundle name length validation work.  So far, I have to edit the `core.rukpak.io_bundles.yaml` after it is generated.  

For ref
```
                          properties:
                            branch:
                              description: Branch refers to the branch to checkout from the repository. The Branch should contain the bundle manifests in the specified directory.
                              type: string
                            commit:
                              description: Commit refers to the commit to checkout from the repository. The Commit should contain the bundle manifests in the specified directory.
                              type: string
                            tag:
                              description: Tag refers to the tag to checkout from the repository. The Tag should contain the bundle manifests in the specified directory.
                              type: string
                          oneOf:
                            - required: ["branch"]
                            - required: ["commit"]
                            - required: ["tag"]
```
For bundle name
```
            metadata:
              type: object
              properties:
                name:
                  type: string
                  maxLength: 40
```
For source (only one the type specified, type match can not be validated)
```
               source:
                  properties:
...
                  oneOf:
                    - required: ["git"]
                    - required: ["image"]

```

I'm thinking about create a script that patch the `core.rukpak.io_bundles.yaml` file after generation.  
The webhook is still needed for full validation.
