### ISSUE TITLE
Git-based bundles do not support custom directory field

### ISSUE THREAD

**Issue by exdx** [operator-framework/rukpak#233]
In the plain bundle spec, it's mentioned that the limitation of having the manifests stored under `./manifests` does not apply to git based bundles, since the `spec.source.git.directory` field exists and a user can point to an arbitrary directory in the repository where the manifests are stored.

However, applying a bundle with a custom directory set results in an error. 
```
k apply -f -<<EOF
apiVersion: core.rukpak.io/v1alpha1
kind: Bundle
metadata:
  name: combo-branch-ref-deploy
spec:
  source:
    type: git
    git:
      ref:
        branch: main
      directory: ./dev/deploy
      repository: https://github.com/exdx/combo-bundle
  provisionerClassName: core.rukpak.io/plain
EOF
```

```
Status:
  Conditions:
    Last Transition Time:  2022-04-08T20:39:37Z
    Message:               get objects from bundle manifests: readdir manifests: file does not exist
    Reason:                UnpackFailed
    Status:                False
    Type:                  Unpacked
```

A/C:
* Determine whether git bundles should in fact have the same limitations as image based bundles
* If so, update the plain bundle spec
* If not, update code to handle arbitrary directories from git based bundles
* Add an e2e test for this scenario

**Comment by joelanford** [comment]
I think this is behaving as expected

```
spec:
  source:
    type: git
    git:
      ref:
        branch: main
      directory: ./dev/deploy
      repository: https://github.com/exdx/combo-bundle
  provisionerClassName: core.rukpak.io/plain
```

This says "Look for a plain manifest bundle rooted at `./dev/deploy`. It looks like the `./dev/deploy` directory is an invalid plain+v0 root because it doesn't contain a `manifests` directory.  To fix this, you need to create `./dev/deploy/manifests` and move the contents of `./dev/deploy` into `./dev/deploy/manifests`.
