### ISSUE TITLE
Support private operator images

### ISSUE THREAD

**Issue by akihikokuroda** [operator-framework/rukpak#275]
This is the second part of https://github.com/operator-framework/rukpak/issues/81

For sourcing images that are within BI manifests, things are more difficult because we would need some way to:

know what secrets to use and where to inject them
actually inject the secret into the pod spec(s) that need them as the BI is being installed. (this sounds a lot like what the cert-manager injection annotations do)

**Comment by akihikokuroda** [comment]
I'm thinking to add the support of variables in BI.  It can be used to add **ImagePullSecret**. 
Because BI uses the helm library to install, it's easy to implement like:

yaml file in the bundle 
```
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.namespace }}"
```  

BI with values
```
apiVersion: core.rukpak.io/v1alpha1
kind: BundleInstance
metadata:
  name: combo
spec:
  provisionerClassName: core.rukpak.io/plain
  bundleName: combo-v0.0.1
  values:
    namespace: namespace-test
```
WDYT?
