### ISSUE TITLE
Successfully installed BundleInstance resources should have a populated status condition message

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#281]
Goal: populate the status condition in the BI controller when a successful installation has occurred with a human readable message.

AC:
- Update [^1] and add a message field
- Update any e2e tests [^2] that codify this previous behavior where an empty string would be produced

When installing a BundleInstance that references a valid, unpacked Bundle, the BI controller is able to perform the reconciliation happy path, and report a successful installation state:

```yaml
apiVersion: core.rukpak.io/v1alpha1
kind: BundleInstance
...
status:
  conditions:
  - lastTransitionTime: "2022-04-28T14:33:08Z"
    message: ""
    reason: InstallationSucceeded
    status: "True"
    type: Installed
...
```

[^1]: <https://github.com/operator-framework/rukpak/blob/main/internal/provisioner/plain/controllers/bundleinstance_controller.go#L265-L269>
[^2]: <https://github.com/operator-framework/rukpak/blob/455aead0f9a3687bdee334d27483ac23d1219a4e/test/e2e/plain_provisioner_test.go#L970>
