### ISSUE TITLE
Helm bundle fails without chart directory with git source

### ISSUE THREAD

**Issue by akihikokuroda** [operator-framework/rukpak#540]
Creating the helm bundle without the chart directory fails with the following error 
```
1.6618967089468236e+09	ERROR	Reconciler error	{"controller": "bundle", "controllerGroup": "core.rukpak.io", "controllerKind": "Bundle", "bundle": {"name":"my-ahoy-dbf4zx"}, "namespace": "", "name": "my-ahoy-dbf4zx", "reconcileID": "2546d990-9bde-4139-b3d8-e9b540fcb10e", "error": "generate tar.gz from FS: cannot open directory: /charts/hello-world"}
```

Here is the BD for this.
```
kind: BundleDeployment
metadata:
  name: my-ahoy
spec:
  provisionerClassName: core-rukpak-io-helm
  template:
    metadata:
      labels:
        app: my-ahoy
    spec:
      provisionerClassName: core-rukpak-io-helm
      source:
        git:
          ref:
            branch: main
          repository: https://github.com/akihikokuroda/examples
          directory: ./charts/hello-world
        type: git
```
