### ISSUE TITLE
v1alpha2 API

### ISSUE THREAD

**Issue by ncdc** [operator-framework/rukpak#703]
I'd like to iterate on our API as we think about moving to a more stable beta/GA version. Here are my thoughts for v1alpha2:

Remove the Bundle CRD entirely. It adds unnecessary complexity that instead can be handled internally by BundleDeployment.

Here's what I'm thinking for BundleDeployment:

```yaml
apiVersion: core.rukpak.io/v1alpha2
kind: BundleDeployment
metadata:
  name: foo
spec:
  paused: true | false
  # sources is a list of places from which we fetch content. We support multiple in case you need to fetch multiple.
  sources:
  - kind: image
    image:
      ref: foo/bar@sha256:123
      auth:
        # I'm not sure if it makes sense to allow the BundleDeployment user to specify a namespace - could be a security concern
        namespace: ns
        name: n
    destination: foo/bar # where to unpack the image's contents in the local fs; useful when you have multiple sources
  - kind: git
    git:
      repository: https://github.com/foo/bar
      ref: a3b1dff2
      directory: '' # what part of the git repo to copy to .destination; leave blank to copy the entire repo
      auth:
        secret:
          # I'm not sure if it makes sense to allow the BundleDeployment user to specify a namespace - could be a security concern
          namespace: foo
          name: my-git-creds
      destination: foo/moo
  - kind: http
    http:
      url: https://path/to/some/tar.gz
      auth:
        secret:
          # I'm not sure if it makes sense to allow the BundleDeployment user to specify a namespace - could be a security concern
          namespace: foo
          name: my-https-creds
      destination: foo/bar
  # format indicates how to handle what we've unpacked. In a future alpha, I'd like to convert this to an array of `processors` so we add support for templating and other mutations. In the spirit of iteration, though, we can consider keeping this a single field in alpha2.
  format: registry-v1 | helm | plain
```

The BundleDeployment controller architecture would change such that there is no longer a provisioner class. That is now controlled by .spec.format. Also, we only need a single instance of the controller; the reconcile function can handle fetching, dealing with the format, and applying to the cluster.

We will probably also want to include `.spec.healthChecks` in some shape, but I haven't thought what that looks like just yet. It might make sense to model it after pod probes.
