### ISSUE TITLE
Support referencing and mounting local Bundle content

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#92]
Right now the Bundle API only supports referencing a spec.Image container image, which gets pulled down through CRI and unpacked at runtime. It would be nice to be able to support configuring a Bundle to source local cluster contents, e.g. a mounted ConfigMap or PVC filesystem path, so we can avoid having to build/push a scratch-based container image.

Example Bundle YAML manifest outlined in the e2e strawman:

```yaml
kind: Bundle
metadata: 
  name: plumbus-operator.v0.9.3
spec:
  class: deppy.resolveset
  refs:
  - file://content
  volumeMounts:
  - mountPath: /content
    configMap:
      name: local 
      namespace: plumbus
```

We could introduce a spec.Source/spec.Refs field to the Bundle API where we only have a single supported source, which is the image source provider, and build out support for referencing local Kubernetes resource for Bundle content.

**Comment by timflannagan** [comment]
Moving this as 0.1 candidate.

**Comment by timflannagan** [comment]
A couple of things I was thinking about locally when playing around with this yesterday:

- Updating the spec.Image field to be spec.Source and ensuring all source types have a valid prefix, e.g. docker://... or image://... for container images, file://... for anything mountable in k8s, s3://... and whether that's a surprising from a UX perspective.
- How does the provisioner behave when there's updates to the underlying PVC/ConfigMap that's referenced in the spec.Source key? Do we setup something like a fsnotify watcher, or does this come back full circle to the Bundle immutability conversation? My current thinking is that I'd like to be able to declaratively make changes to my Bundle's source-of-truth (e.g. a ConfigMap/PVC in this case) and see the provisioner propagate those changes. Do I need to create another Bundle in order to enable that use case? That seems like it waters down the value proposition but maybe I'm thinking about this in the wrong way.
- How does the provisioner handle flapping between source types? Does this wrap back into the Bundle immutability conversation, or do we need a somewhat first-class way of ensuring Bundles that declare a certain source type _cannot_ be changed after creation?
- It feels like we need validation for when the spec.Source: file://... key is present to ensure that the spec.VolumeMounts configuration is also present for how the e2e strawman outlined in the Bundle API.
- Do we support updating the volume mounts specified for a Bundle?

**Comment by timflannagan** [comment]
cc @joelanford in case you have any thoughts as well. I think this is a natural "next big feature" in my mind once we shore up the plain/v0 provisioner, so it would be nice to get consensus on a direction, get feedback, and then re-assess whether this was the right approach as we lean towards GA status.

**Comment by joelanford** [comment]
> valid prefix

I think the trouble with a prefix-based approach is that there's an assumption that the configuration for sourcing the `source` is applicable to all source prefixes. 

> My current thinking is that I'd like to be able to declaratively make changes to my Bundle's source-of-truth (e.g. a ConfigMap/PVC in this case) and see the provisioner propagate those changes

Conceptually, I keep thinking of putting an image tag in a pod spec. The pod controller doesn't monitor for changes to the tag's SHA. Once a pod's image is resolved to a SHA, that's it. That pod is forever running an image with what SHA. You want a new SHA? Re-spin the pod.

I think of `BundleInstance` as a `Pod`, and the `Bundle` as the `pod.spec.image`. The bundle updates its content when its underlying source of truth changes, but that doesn't propagate to a running `BundleInstance`.

In the case of deployments/replicasets and stateful sets, there's a higher level controller managing pods. So if something deletes one of those managed pods, those controllers will create a new one. And in _that_ case, the new pod could pick up a new image SHA.

I think that same sort of architecture will exist on top of `BundleInstance`.

> How does the provisioner handle flapping between source types? Does this wrap back into the Bundle immutability conversation, or do we need a somewhat first-class way of ensuring Bundles that declare a certain source type cannot be changed after creation?

I might be missing something, but if we end up saying bundles are mutable, why would we care about the source type changing?

> It feels like we need validation for when the spec.Source: file://... key is present to ensure that the spec.VolumeMounts configuration is also present for how the e2e strawman outlined in the Bundle API.

This gets back to my first point about the issue with prefix-based sources. It seems like it would be easier:
1. to validate a `source` union type, that has `file` subtype with configuration specific to that source (`volumeMounts`)
2. for a user of the API to understand. In the union type case `volumeMounts` is a required field in the `file` field. In the prefixed source case, its an optional field, but its required if the prefix of `spec.source` is `file://`. Oh and it's complete inert if the prefix of `spec.source` is anything else. That's the _exact_ problem we have with the `CatalogSource` API.

IMO, this:
``` yaml
spec:
  source:
    file: #exactly one of source.* fields required
      path: /content # required
      volumeMounts: # required
      - mountPath: /content
        configMap:
          name: local 
          namespace: plumbus
```
is more ergonomic than:
```yaml
spec:
  class: deppy.resolveset
  refs:
  - file://content
  volumeMounts: # required when refs prefixed with "file://", ignored otherwise
  - mountPath: /content
    configMap:
      name: local 
      namespace: plumbus
```

> Do we support updating the volume mounts specified for a Bundle?

IMO, that depends on where we end up on the design for bundle immutability and propagation to bundle instances.

> Should we roll out this kind of functionality over time, e.g. support mounting ConfigMaps, then PVCs, etc.?

I think we need to assume that we'll need to expand the set of supported sources over time, so I think the important thing to get right at the beginning is the extensibility of the API. We need the API to support introducing new sources in a backwards compatible way.
