### ISSUE TITLE
Add support for label selection of Bundles in the BundleInstance API

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#94]
Goal: mirror the deployment/replicaset pattern and update the BundleInstance API to have a spec field that contains a label selector to enable pivoting decisions between Bundles that all contain the same label. The underlying provisioner is responsible for making these pivoting decisions.

Example BundleInstance resource that was outlined in the original e2e strawman:

```yaml
kind: BundleInstance
metadata:
  name: etcd-operator
spec:
  selector: 
    matchLabels:
      subscription: etcd-operator
```
